version: '3.7'

services:
  frontend:
    container_name: frontend
    image: 'node:16.7'
    volumes:
      - ./moneyapp:/home/node/app
    ports:
      - 8100:8100
    stdin_open: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=https://money-app-nqproject-staging.herokuapp.com/
    working_dir: /home/node/app
    user: "node"
    command: /home/node/app/entrypoint.sh